name: Homelab Setup
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer_data:/data
include:
  - ./arr/docker-compose.yml
  - ./infra/docker-compose.yml
  - ./media/docker-compose.yml
  - ./backup/docker-compose.yml
  - ./tools/docker-compose.yml
networks:
  homelab:
    name: ${NETWORK_NAME}
    external: true
