name: Homelab Setup
include:
  - ./arr/docker-compose.yml
  - ./infra/docker-compose.yml
  - ./media/docker-compose.yml
  - ./backup/docker-compose.yml
  - ./tools/docker-compose.yml
networks:
  homelab:
    external: true
