- Info:
    - Calender:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: agenda
          maxEvents: 10
          showTime: true
          timezone: Asia/Kolkata
          integrations:
            - type: sonarr
              service_group: ARR
              service_name: Sonarr
              color: teal
              baseUrl: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8989
              params:
                unmonitored: true
            - type: radarr
              service_group: ARR
              service_name: Radarr
              color: teal
              baseUrl: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:7878
              params:
                unmonitored: true
- Infra:
    - Gluetun:
        icon: gluetun.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8000
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8000
        server: druv-docker
        container: gluetun
        widget:
          type: gluetun
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8000
    - Airtel Speed:
        icon: myspeed.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5217
        widget:
          type: myspeed
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5217
    - VPN Speed:
        icon: myspeed.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5216
        widget:
          type: myspeed
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5216
    - Tailscale:
        icon: tailscale.png
        widget:
          type: tailscale
          deviceid: nhJ5mxzyWt11CNTRL
          key: "{{HOMEPAGE_VAR_TAILSCALE_API_KEY}}"
    - Backup Status:
        icon: backrest.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9898
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9898
        server: druv-docker
        container: backrest
        widget:
          type: backrest
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9898
          username: "{{HOMEPAGE_VAR_RESTIC_USERNAME}}"
          password: "{{HOMEPAGE_VAR_RESTIC_PASSWORD}}"
    - Uptime:
        icon: https://uptime.kuma.pet/img/icon.svg
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:3001
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:3001
        server: druv-docker
        container: uptime-kuma
        widget:
          type: uptimekuma
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:3001
          slug: prinzpiuz
    - Beszel:
        icon: beszel.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8090
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8090
        server: druv-docker
        container: beszel
        widget:
          type: beszel
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8090
          username: "{{HOMEPAGE_VAR_BESZEL_USERNAME}}"
          password: "{{HOMEPAGE_VAR_BESZEL_PASSWORD}}"
          version: 2
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8096
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8096
        server: druv-docker
        container: jellyfin
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          version: 2
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true
    - Audiobookshelf:
        icon: audiobookshelf.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8585
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8585
        server: druv-docker
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8585
          key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY}}"
    - Music:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8100
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8100
        server: druv-docker
        container: jellyfin-music
- ARR:
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5055
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5055
        server: druv-docker
        container: jellyseerr
        widget:
          type: jellyseerr
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5055
          key: "{{HOMEPAGE_VAR_JELLYSEER_API_KEY}}"
    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:7878
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:7878
        server: druv-docker
        container: radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
    - Sonarr:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8989
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8989
        server: druv-docker
        container: sonarr
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
    - Synthwave:
        icon: https://raw.githubusercontent.com/PranavVerma-droid/Synthwave/refs/heads/master/static/logo/logo.jpg
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5000
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:5000
        server: druv-docker
        container: qdrant
    - Prowlarr:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9696
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9696
        server: druv-docker
        container: prowlarr
        widget:
          type: prowlarr
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
    - Jackett:
        icon: jackett.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9117
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9117
        server: druv-docker
        container: jackett
        widget:
          type: jackett
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:9117
          password: "{{HOMEPAGE_VAR_JACKETT_API_KEY}}"
    - Qbittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8080
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8080
        server: druv-docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8080
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
    - Bazarr:
        icon: bazarr.png
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:6767
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:6767
        server: druv-docker
        container: bazarr
        widget:
          type: bazarr
          url: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
- Tools:
    - Filebrowser:
        icon: https://filebrowserquantum.com/logo.svg
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8091
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8091
        server: druv-docker
        container: filebrowser
    - PDF Tools:
        icon: https://raw.githubusercontent.com/alam00000/bentopdf/eb60bbe771f578a3eb609718ad0e01d92dcae1ac/public/images/favicon-no-bg.svg
        href: https://pdftools.prinzpiuz.in
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8085
        server: druv-docker
        container: bentopdf
    - Qdrant:
        icon: https://qdrant.tech/img/qdrant-logo.svg
        href: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:6333/dashboard
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:6333/dashboard
        server: druv-docker
        container: qdrant
    - Location:
        icon: https://dawarich.app/img/logo.svg
        href: https://timeline.prinzpiuz.in
        ping: https://{{HOMEPAGE_VAR_HOMELAB_IP}}:8086
        server: druv-docker
        container: dawarich_app
    - BloTils:
        icon: https://raw.githubusercontent.com/prinzpiuz/BloTils/refs/heads/staging/static/favicon/android-chrome-512x512.png
        href: https://blotils.prinzpiuz.in
        ping: http://{{HOMEPAGE_VAR_HOMELAB_IP}}:8087
        server: druv-docker
        container: blotils
