# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- greeting:
    text_size: xl
    text: Druv v3.0
- logo:
    icon: https://upload.wikimedia.org/wikipedia/commons/6/66/Openlogo-debianV2.svg
- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: 0 # optional, minimum cpu temp
    tempmax: 100 # optional, maximum cpu temp
    uptime: true
    units: metric # only used by cpu temp
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
    network: true
- datetime:
    text_size: xl
    format:
      timeStyle: short
