name: Tools
include:
  - path: ./dawarich/docker-compose.yml
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    pull_policy: always
    ports:
      - 6333:6333
    volumes:
      - /data/qdrant_storage:/qdrant/storage:z
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest
    container_name: bentopdf
    restart: unless-stopped
    pull_policy: always
    ports:
      - 8085:8080
