- Info:
    - Calender:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: agenda
          maxEvents: 10
          showTime: true
          timezone: Asia/Kolkata
          integrations:
            - type: sonarr
              service_group: Services
              service_name: Sonarr
              color: teal
              params:
                unmonitored: true
            - type: radarr
              service_group: Services
              service_name: Radarr
              color: teal
              params:
                unmonitored: true
    - Gluetun:
        icon: gluetun.png
        href: http://192.168.1.10:8000
        ping: http://192.168.1.10:8000
        server: druv-docker
        container: gluetun
        widget:
          type: gluetun
          url: http://192.168.1.10:8000
    - Portainer:
        icon: portainer.png
        href: http://192.168.1.10:9000
        ping: http://192.168.1.10:9000
        server: druv-docker
        container: portainer
        widget:
          type: portainer
          url: http://192.168.1.10:9000
          env: 3
          key: ptr_c9uY2eouAzKEF5Ca1sfWIEmWc0owvzftt4kKyYFmevU=
    - S.M.A.R.T:
        icon: scrutiny.png
        href: http://192.168.1.10:8081
        widget:
          type: scrutiny
          url: http://192.168.1.10:8081
    - Airtel Speed:
        href: http://192.168.1.10:5217
        widget:
          type: myspeed
          url: http://192.168.1.10:5217
    - VPN:
        href: http://192.168.1.10:5216
        widget:
          type: myspeed
          url: http://192.168.1.10:5216
    - Tailscale:
        widget:
          type: tailscale
          deviceid: nhJ5mxzyWt11CNTRL
          key: {? {HOMEPAGE_VAR_TAILSCALE_API_KEY: ''} : ''}
- Services:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.10:8096
        ping: http://192.168.1.10:8096
        server: druv-docker
        container: jellyfin
        widget:
          type: jellyfin
          url: http://192.168.1.10:8096
          key: df3329ed0ccc4852b3668dbbb63a27c2
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://192.168.1.10:5055
        ping: http://192.168.1.10:5055
        server: druv-docker
        container: jellyseerr
        widget:
          type: jellyseerr
          url: http://192.168.1.10:5055
          key: MTczNjMxNDAxODYzMWY3NjBhZGZmLTQ3MjMtNDhhNy1hNTA0LTk5MDc3Y2Q0OGFjYg==
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.10:7878
        ping: http://192.168.1.10:7878
        server: druv-docker
        container: radarr
        widget:
          type: radarr
          url: http://192.168.1.10:7878
          key: d171c00a200f49a282a3f9b2e4c8a8ba
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.10:8989
        ping: http://192.168.1.10:8989
        server: druv-docker
        container: sonarr
        widget:
          type: sonarr
          url: http://192.168.1.10:8989
          key: 517ad724ae8a45b18e3c637538b70c02
    - Readarr:
        icon: readarr.png
        href: http://192.168.1.10:8787
        ping: http://192.168.1.10:8787
        server: druv-docker
        container: readarr
        widget:
          type: readarr
          url: http://192.168.1.10:8787
          key: 0e405e79238b499fb2b8d15527b3904b
    - audiobookshelf:
        icon: audiobookshelf.png
        href: http://192.168.1.10:8585
        ping: http://192.168.1.10:8585
        server: druv-docker
        container: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://192.168.1.10:8585
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZThkMmFiOC0yZDA3LTRkNzItYjA4ZC04NWVlOGY4ZDVlMTUiLCJ1c2VybmFtZSI6ImRydXYiLCJpYXQiOjE3NDkyMzAyOTR9.4vM8rcnQux737uql24wz93EHS6xTqBTrrXJF3mP11RU
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.1.10:9696
        ping: http://192.168.1.10:9696
        server: druv-docker
        container: prowlarr
        widget:
          type: prowlarr
          url: http://192.168.1.10:9696
          key: afdd40b1c55e4411b810e43f2f3cbec0
    - Jackett:
        icon: jackett.png
        href: http://192.168.1.10:9117
        ping: http://192.168.1.10:9117
        server: druv-docker
        container: jackett
        widget:
          type: jackett
          url: http://192.168.1.10:9117
          password: T5hdvC#PKcts6
    - Qbittorrent:
        icon: qbittorrent.png
        href: http://192.168.1.10:8080
        ping: http://192.168.1.10:8080
        server: druv-docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://192.168.1.10:8080
          username: druv
          password: T5hdvC#PKcts6
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.1.10:6767
        ping: http://192.168.1.10:6767
        server: druv-docker
        container: bazarr
        widget:
          type: bazarr
          url: http://192.168.1.10:6767
          key: 611883da04f4fc9fb9d7fb3de7073835
